packages:
  - 'client'
  - 'server'

catalog:
  ox: "^0.6.9"
  viem: "^2.23.0"
  porto: "^0.0.11"
  wagmi: "^2.14.11"
  wrangler: "^3.107.3"
  typescript: "^5.7.3"
  '@wagmi/core': "^2.16.4"
  '@types/node': "^22.13.1"
